apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: alexeygoderpipelinesjavascriptdocker 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: alexeygoderpipelinesjavascriptdocker 
    spec:
      containers:
        - name: alexeygoderpipelinesjavascriptdocker 
          image: alexeycontainerregistry.azurecr.io/alexeygoderpipelinesjavascriptdocker
          ports:
          - containerPort: 8080